export type NamingConvention =
    | "camelCase"
    | "PascalCase"
    | "snake_case"
    | "kebab-case"
    | "SCREAMING_SNAKE_CASE"
    | "COBOL-CASE"
    | "BEM"
    | "UPPERCASE"
    | "lowercase"
    | "dot.case"
    | "space case"
    | "Title Case"
    | "Train-Case"
    | "camel_snake_case"
    | "Hungarian"
    | "namespace"
    | "css-variable"
    | "env_variable"
    | "hex"
    | "uuid_v4"
    | "sql_case"
    | "noCase"
    | "unknown";